steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/be-trigger-alungnajib", "."]
    dir: 'backend'

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/be-trigger-alungnajib"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be-trigger-alungnajib",
        "--image",
        "gcr.io/$PROJECT_ID/be-trigger-alungnajib",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "NODE_ENV=${_NODE_ENV},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASS=${_DB_PASS},DB_USER=${_DB_USER},JWT_SECRET=${_JWT_SECRET},JWT_EXPIRES_IN=${_JWT_EXPIRES_IN}"
      ]

options:
  logging: CLOUD_LOGGING_ONLY